nmap <buffer> <CR> <plug>(bqn_eval_till_line)
xmap <buffer> <CR> <plug>(bqn_eval_range)
nmap <buffer> <leader>bf <plug>(bqn_eval_file)
nmap <buffer> <leader>bc <plug>(bqn_clear_after_line)
xmap <buffer> <leader>bc <plug>(bqn_clear_range)
